- name: variable preference 
  hosts: local
  connection: local
  vars:
    NAME: Hello Gokul
  vars_files:
  - course.yaml
  vars_prompt:
  - name: NAME 
    prompt: what is your NAME?
    private: false
  tasks:
  - name: testing variable preferences
    vars:
      tfromfromfrlevelfrom task level
